### ISSUE TITLE
step2_pretrain_mlm.py 是否支持bert的finetune

### ISSUE THREAD

**Issue by seun-wun** [whgaara/pytorch-roberta#1]
你好，我需要用bert模型完成文本纠错。但是我发现在step2_pretrain_mlm.py 中只有用roberta训练的过程，似乎并不支持bert网络。请问要如何用bert完成基于数据集的finetune的后续的inference呢？

**Comment by whgaara** [comment]
按理说不会啊，你看下pretrain config文件，那里有设置模式的，默认就是bert模式。但是如果要加载符合你预期的预训练模型，可能要稍稍修改下代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月21日 23:28
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
你好，我需要用bert模型完成文本纠错。但是我发现在step2_pretrain_mlm.py 中只有用roberta训练的过程，似乎并不支持bert网络。请问要如何用bert完成基于数据集的finetune的后续的inference呢？

**Comment by whgaara** [comment]
另外roberta和bert其实本质没啥区别，用啥都可以。他们transformer部分是一模一样的，也就是做数据预处理有点区别。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月21日 23:28
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
你好，我需要用bert模型完成文本纠错。但是我发现在step2_pretrain_mlm.py 中只有用roberta训练的过程，似乎并不支持bert网络。请问要如何用bert完成基于数据集的finetune的后续的inference呢？

**Comment by seun-wun** [comment]
哦哦 我看到了，是在roberta文件夹里面设置了 ModelClass的选择 谢谢！

**Comment by whgaara** [comment]
是的，这个文件夹只是个还没来得及改的网络层文件夹名，容易引起误会。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月21日 23:42
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
哦哦 我看到了，是在roberta文件夹里面设置了 ModelClass的选择 谢谢！

**Comment by seun-wun** [comment]
你好 我在step2_pretrain_mlm.py的过程中遇到了bug 
Traceback (most recent call last):
  File "pytorch-roberta-master/train_module/mlm_module/step2_pretrain_mlm.py", line 30, in <module>
    roberta.load_pretrain(SentenceLength)
  File "../../roberta/layers/Roberta_mlm.py", line 85, in load_pretrain
    finetune_model_dict = pretrain_model_dict.state_dict()
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

我把pretrain_config.py中的pretrain_path修改了
```
if ModelClass == 'Bert':
    RepeatNum = 1
    BatchSize = 16
    SentenceLength = 128
    # PretrainPath = '../../checkpoint/finetune/mlm_trained_%s.model' % SentenceLength
    PretrainPath = '../../checkpoint/pretrain/pytorch_model.bin'
```
checkpoint/pretrain文件夹下分别是
```
bert_config.json
pytorch_model.bin
vocab.txt
```

请问你有遇到过这个问题吗？另外想问一下torch的版本~

**Comment by seun-wun** [comment]
你好 我在训练时发生了问题
```
RuntimeError: Error(s) in loading state_dict for RobertaMlm:
	size mismatch for roberta_emd.token_embeddings.weight: copying a param with shape torch.Size([21128, 768]) from checkpoint, the shape in current model is torch.Size([21159, 768]).
```
我已经将SentenceLength改成512，HiddenLayerNum改成12。
我使用的预训练模型是chinese_wwn_pytorch,解压后放在checkpoint/pretrain目录下
```
bert_config.json
pytorch_model.bin
vocab.txt
```
请问您有遇到过这个问题吗？ 另外想问一下torch的版本

**Comment by whgaara** [comment]
是这样，这是因为你用的vocab.txt文件中字符个数和预训练中使用vocab.txt文件的字符个数不匹配导致的。你休息下，这个要一致，因为这个个数直接决定了embedding层的维度



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 00:31
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
你好 我在训练时发生了问题
 RuntimeError: Error(s) in loading state_dict for RobertaMlm: size mismatch for roberta_emd.token_embeddings.weight: copying a param with shape torch.Size([21128, 768]) from checkpoint, the shape in current model is torch.Size([21159, 768]).  
我已经将SentenceLength改成512，HiddenLayerNum改成12。
 我使用的预训练模型是chinese_wwn_pytorch,解压后放在checkpoint/pretrain目录下
 bert_config.json pytorch_model.bin vocab.txt  
请问您有遇到过这个问题吗？ 另外想问一下torch的版本

**Comment by seun-wun** [comment]
我改好这个问题了，是我自己的训练数据集中有一些字符不在预训练模型的vocab.txt中，我把那些字符加进去，就出现了错误。现在已经可以训练了。
不过训练数据集中不在vocab.txt中的字符要加到哪里呢？加到vocab_bk.txt中吗？

**Comment by whgaara** [comment]
不，如果你一定要用预训练，这个问题你只能用两种方法解决，第一是不管他们，这样他们会被unk字符代替，第二是将新字符替换任意原来vocab文件中不重要的字符，vocab bk只是我用来备份的，没用。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 00:38
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
我改好这个问题了，是我自己的训练数据集中有一些字符不在预训练模型的vocab.txt中，我把那些字符加进去，就出现了错误。现在已经可以训练了。
 不过训练数据集中不在vocab.txt中的字符要加到哪里呢？加到vocab_bk.txt中吗？

**Comment by seun-wun** [comment]
好的，非常感谢！

**Comment by whgaara** [comment]
不客气，方便透露下你现在是学生还是在哪家单位就职？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 00:48
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
好的，非常感谢！

**Comment by seun-wun** [comment]
我毕业一年多了，现在在电商平台工作，不过之前做的不是NLP相关的。

**Comment by seun-wun** [comment]
你好，我用训练数据训练了9个epoch，但是对预测数据的预测效果并不好
```
句子正确个数：1，句子总共个数：70，句子正确率：0.01
句子纠错个数：8，句子未纠正个数：69，句子纠错率：0.12
top1正确个数：2713，top1总共个数：2801，top1正确率：0.97
top5正确个数：2719，top5总共个数：2801，top5正确率：0.97
```
请问，这个模型是对较短的句子的预测效果比较好吗？我看到项目中的数据都是较短的句子。我预测正确的一个句子也是较短的，其他的句子都很长。

**Comment by whgaara** [comment]
首先你代码可能没更新，最近我修复里面的一些问题。
你再次跑的时候注意把config文件中的隐藏层给调小一点，大概2-6层即可。
另外纠错这种能达到90%以上其实就算不错了，你可以了解下目前纠错的普遍效果先。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 19:18
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
你好，我用训练数据训练了9个epoch，但是对预测数据的预测效果并不好
 句子正确个数：1，句子总共个数：70，句子正确率：0.01 句子纠错个数：8，句子未纠正个数：69，句子纠错率：0.12 top1正确个数：2713，top1总共个数：2801，top1正确率：0.97 top5正确个数：2719，top5总共个数：2801，top5正确率：0.97  
请问，这个模型是对较短的句子的预测效果比较好吗？我看到项目中的数据都是较短的句子。我预测正确的一个句子也是较短的，其他的句子都很长。

**Comment by seun-wun** [comment]
这个纠错90%是按照top1的正确率算的吗，但是我70个句子，只有一个是检测到正确的错别字并纠正对了。我的句子一般较长，隐藏层也是设置为2-6层吗？

**Comment by seun-wun** [comment]
训练数据需要把标点去掉吗？

**Comment by whgaara** [comment]
你可以用一些小训练集做尝试，先用6层，不行再加。最关键你要更新代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 19:27
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
这个纠错90%是按照top1的正确率算的吗，但是我70个句子，只有一个是检测到正确的错别字并纠正对了。我的句子一般较长，隐藏层也是设置为2-6层吗？

**Comment by whgaara** [comment]
一些冷门字符可以去掉，正常的标点不用的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seun-wun <notifications@github.com&gt;
发送时间: 2020年11月22日 19:33
收件人: whgaara/pytorch-roberta <pytorch-roberta@noreply.github.com&gt;
抄送: next door <695509060@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[whgaara/pytorch-roberta] step2_pretrain_mlm.py 是否支持bert的finetune (#1)





 
训练数据需要把标点去掉吗？
